export class Constants {
    static ES: any = {
        analisysError: "Se han encontrado incompatibilidades. Seguir con la copia puede producir inconsistencias.",
        analisysErrorInternalName: "[Error] Nombre interno no encontrado: %1",
        analisysErrorInternalNameAndType: "[Advertencia] Campo '%1' no tiene el mismo tipo de dato",
        analisysErrorRequired: "[Error] Campo '%1' es requerido en destino",
        directoryPermissionsSite: "Permisos del sitio",
        explorerBibliotecaTitulo: "Biblioteca",
        explorerBibliotecaInternal: "Nombre interno",
        explorerBibliotecaEntityType: "Nombre entidad",
        explorerBibliotecas: "Bibliotecas",
        explorerCargando: "Cargando",
        explorerListas: "Listas",
        explorerNoRows: "Lista vacía",
        explorerSubsitios: "Sub-Sitios",
        explorerSubsitiosEstructura: "Mostrar estructura",
        explorerHelp: "Seleccione un recurso del menú lateral",
        explorerMenuBotonCopiar: "Copiar",
        explorerMenuBotonDescargar: "Descargar",
        explorerMenuBotonEliminar: "Eliminar",
        explorerMenuBotonPegar: "Pegar",
        explorerMenuBotonPegarFolder: "Pegar en carpeta",
        explorerMenuBotonRefrescar: "Refrescar",
        explorerMenuBotonSubirCSV: "Importar CSV",
        explorerMenuDesplegableVista: "Vista",
        explorerModalComprimir: "Compresión de archivo",
        explorerModalCopyTitle: "Copiar y Pegar",
        explorerModalCopyMessage: "Copiando archivo {%1} / {%2} ({%3} Errores)",
        explorerModalCopyMessageList: "Copiando ítem {%1} / {%2} ({%3} Errores)",
        explorerModalCopyMessageFinished: "Copia finalizada {%1} / {%2} ({%3} Errores)",
        explorerModalCopyMessageAnalysing: "Analizando lista destino...",
        explorerModalCopyMessageConfirm: "ADVERTENCIA: Se va a pegar el contenido seleccionado creando las carpetas y sobreescribiendo archivos existentes. ¿Aceptar y continuar?",
        explorerModalCopyMessageConfirmList: "ADVERTENCIA: Se va a pegar el contenido seleccionado en esta lista. ¿Aceptar y continuar?",
        explorerModalCopyMessageFolderConfirm: "ADVERTENCIA: Se va a pegar el contenido seleccionado ignorando la estructura de carpetas y sobreescribiendo archivos existentes en la carpeta seleccionada. ¿Aceptar y continuar?",
        explorerModalDeleteTitle: "Eliminación",
        explorerModalDeleteMessage: "Eliminando archivo {%1} / {%2} ({%3} Errores)",
        explorerModalDeleteMessageList: "Eliminando ítem {%1} / {%2} ({%3} Errores)",
        explorerModalDeleteMessageFinished: "Eliminación finalizada {%1} / {%2} ({%3} Errores)",
        explorerModalDeleteMessageConfirm: "ADVERTENCIA: Se va a eliminar el contenido seleccionado. ¿Aceptar y continuar?",
        explorerModalDescargar: "Descarga de archivo",
        explorerModalDescargarErrores: "Errores de descarga",
        explorerModalDescargarTitulo: "Descargando archivos",
        explorerModalDescargarCompletado: "Descargado",
        explorerModalExcelTitle: "Descargar hoja Excel",
        explorerModalExcelMessage: "Todas las filas seleccionadas de la vista actual se descargarán como un fichero separado por coma (csv), compatible con Excel.",
        explorerModalExcelMessage2: "Para una correcta compatiblidad con Excel, debe seleccionar el carácter separador correcto para el idioma de tu sistema.",
        explorerModalExcelMessage3: "Separador",
        explorerModalExcelOption1: "Coma (,)",
        explorerModalExcelOption2: "Punto y Coma (;)",
        explorerModalImportExcelTitle: "Importar hoja Excel",
        explorerModalImportExcelMessage: "Seleccionar el archivo CSV que se desea importar en esta lista.",
        explorerModalImportExcelMessage2: "Para una correcta carga, debe seleccionar el carácter separador utilizado en el archivo.",
        explorerModalImportExcelMessage3: "Comenzar la importación de datos en SharePoint.",
        explorerModalImportExcelMessage4: "La información leída del fichero será importada en la lista.",
        explorerModalImportExcelMessageErrorsFound: "¡Atención! Errores encontrados. Pueden causar corrupción en la información. Se recomienda corregir estas incidencias antes de continuar.",
        explorerModalImportExcelMessage5: "Importando información a SharePoint.",
        explorerModalImportExcelMessage6: "Esto puede tardar un momento. Puedes cancelar la operación en cualquier momento.",
        explorerModalImportExcelMessage7: "Importación finalizada.",
        explorerModalImportExcelAnalyze: "Cargar fichero",
        explorerModalImportExcelMessageProcessing: "Procesando",
        explorerModalImportExcelMessageReading: "Fichero leído",
        explorerModalImportExcelMessageUploading: "Importado en la lista",
        explorerModalImportExcelError: "Error de fichero",
        explorerModalImportExcelError01: "No es del tipo esperado",
        libraryViewerCargando: "Cargando bilblioteca",
        libraryViewerCargandoItems: "Cargando datos de la biblioteca",
        libraryViewerCargarListaCompleta: "Cargar lista completa",
        libraryViewerFolder: "Carpeta",
        libraryViewerItemsCargados: "Items cargados",
        libraryViewerTotalItems: "Items en total",
        menuAccesoDenegado: "Access Denied",
        menuAnalizandoSitio: "Analizando Sitio",
        menuConectado: "Conectado",
        menuDirectory: "Directorio",
        menuExplorador: "Explorador",
        menuLCID: "LCID",
        menuNoSharePoint: "Sin Conexión",
        menuTitulo: "Título",
        menuVersion: "Versión UI",
        webViewerCargando: "Cargando web",
        webViewerDetailsUnauzorized: "Web acceso no autorizado",
        webViewerDetailsExploreWeb: "Explorar",
        webViewerDetailsLevelLimit: "Alcanzado límite de 100 niveles de subsitio",
        generalCreado: "Creado",
        generalDescripcion: "Descripción",
        generalSitio: "Sitio",
        generalBotonAceptar: "Aceptar",
        generalBotonCerrar: "Cerrar",
        generalBotonCancelar: "Cancelar",
        generalBotonDescargar: "Descargar",
        generalBotonCargar: "Cargar",
        generalBotonImportar: "Importar",
        generalTrue: "Verdadero",
        generalFalse: "Falso",
        generalSi: "Sí",
        generalNo: "No"
    };
    static EN: any = {
        analisysError: "Incompatibilities found. Proceed to copy may cause issues.",
        analisysErrorInternalName: "[Error] Internal name not found: %1",
        analisysErrorInternalNameAndType: "[Warning] The field '%1' is not the same data type",
        analisysErrorRequired: "[Error] Field '%1' is required on target list",
        directoryPermissionsSite: "Site permissions",
        explorerBibliotecaTitulo: "Library",
        explorerBibliotecaInternal: "Internal name",
        explorerBibliotecaEntityType: "Full entity",
        explorerBibliotecas: "Libraries",
        explorerCargando: "Loading",
        explorerListas: "Lists",
        explorerNoRows: "Empty list",
        explorerSubsitios: "Sub-Sites",
        explorerSubsitiosEstructura: "Show structure",
        explorerHelp: "Select a resource from the left panel",
        explorerMenuBotonCopiar: "Copy",
        explorerMenuBotonDescargar: "Download",
        explorerMenuBotonEliminar: "Delete",
        explorerMenuBotonPegar: "Paste",
        explorerMenuBotonPegarFolder: "Paste in folder",
        explorerMenuBotonRefrescar: "Refresh",
        explorerMenuBotonSubirCSV: "Import CSV",
        explorerMenuDesplegableVista: "View",
        explorerModalComprimir: "Compressing file",
        explorerModalCopyTitle: "Copy & Paste",
        explorerModalCopyMessage: "Copying file {%1} / {%2} ({%3} Errors)",
        explorerModalCopyMessageList: "Copying item {%1} / {%2} ({%3} Errors)",
        explorerModalCopyMessageFinished: "Copy finished {%1} / {%2} ({%3} Errors)",
        explorerModalCopyMessageAnalysing: "Analyzing target list...",
        explorerModalCopyMessageConfirm: "WARNING: Selected content will be saved creating folders and overwriting existing files. Accept and continue?",
        explorerModalCopyMessageFolderConfirm: "WARNING: Selected content will be saved ignoring folder structure and overwriting existing files in the selected folder. Accept and continue?",
        explorerModalDeleteTitle: "Delete",
        explorerModalDeleteMessage: "Deleting file {%1} / {%2} ({%3} Errors)",
        explorerModalDeleteMessageList: "Deleting item {%1} / {%2} ({%3} Errors)",
        explorerModalDeleteMessageFinished: "Delete finished {%1} / {%2} ({%3} Errors)",
        explorerModalDeleteMessageConfirm: "WARNING: Selected content will be deleted. Accept and continue?",
        explorerModalDescargar: "Downloading file",
        explorerModalDescargarErrores: "Download Errors",
        explorerModalDescargarTitulo: "Downloading files",
        explorerModalDescargarCompletado: "Downloaded",
        explorerModalExcelTitle: "Download Excel sheet",
        explorerModalExcelMessage: "All selected rows in the current view will be downloaded as a comma-separated-value (csv) file compatible with Excel.",
        explorerModalExcelMessage2: "To ensure compatibility, Excel requires you to use the proper delimiter for your systems language.",
        explorerModalExcelMessage3: "Delimiter",
        explorerModalExcelOption1: "Comma (,)",
        explorerModalExcelOption2: "Semicolon (;)",
        explorerModalImportExcelTitle: "Import Excel sheet",
        explorerModalImportExcelMessage: "Select the CSV file you wish to import into this list.",
        explorerModalImportExcelMessage2: "To ensure proper loading, we require you to specify the delimiter used in the file.",
        explorerModalImportExcelMessage3: "Start uploading data to SharePoint.",
        explorerModalImportExcelMessage4: "All data read from the file will be uploaded into the list.",
        explorerModalImportExcelMessageErrorsFound: "Important! Please check these errors found. They could cause data corruption. It is recommended to fix these problems before continuing.",
        explorerModalImportExcelMessage5: "Uploading data to SharePoint.",
        explorerModalImportExcelMessage6: "This make take a while. You may cancel at any time.",
        explorerModalImportExcelMessage7: "Import finished.",
        explorerModalImportExcelAnalyze: "Read file",
        explorerModalImportExcelMessageProcessing: "Processing",
        explorerModalImportExcelMessageReading: "File read",
        explorerModalImportExcelMessageUploading: "Uploaded to the list",
        explorerModalImportExcelError: "File error",
        explorerModalImportExcelError01: "Not of the type expected",
        libraryViewerCargando: "Loading library",
        libraryViewerCargandoItems: "Loading library data",
        libraryViewerCargarListaCompleta: "Load full list",
        libraryViewerFolder: "Folder",
        libraryViewerItemsCargados: "Loaded Items",
        libraryViewerTotalItems: "Total Items",
        menuAccesoDenegado: "Acceso Denegado",
        menuAnalizandoSitio: "Analyzing Site",
        menuConectado: "Connected",
        menuDirectory: "Directory",
        menuExplorador: "Explorer",
        menuLCID: "LCID",
        menuNoSharePoint: "Not Connected",
        menuTitulo: "Title",
        menuVersion: "UI Version",
        webViewerCargando: "Cargando web",
        webViewerDetailsUnauzorized: "Web access not autorized",
        webViewerDetailsExploreWeb: "Explore",
        webViewerDetailsLevelLimit: "Subsite levels limited to 100",
        generalCreado: "Created",
        generalDescripcion: "Description",
        generalSitio: "Site",
        generalBotonAceptar: "Accept",
        generalBotonCerrar: "Close",
        generalBotonCancelar: "Cancel",
        generalBotonDescargar: "Download",
        generalBotonCargar: "Load",
        generalBotonImportar: "Import",
        generalTrue: "True",
        generalFalse: "False",
        generalSi: "Yes",
        generalNo: "No"
    };

    private static currentLCID: string = null;

    public static getLiteral(id: string) {
        let text: string;
        if (this.currentLCID === null) {
            this.currentLCID = Constants.getLCID();
        }
        if (this.currentLCID === "es") {
            text = Constants.ES[id];
        } else {
            text = Constants.EN[id];
        }
        return (!text) ? id : text; //if undefined (doesn't exist) just throw out the id string, easier to spot than a blank space
    }

    public static getLCID(): string {
        let lcid = browser.i18n.getUILanguage();
        if (lcid.length > 2) {
            lcid = lcid.substr(0, 2);
        }
        return lcid;
    }

}
